#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}Variables:${NC}"
echo -e "BK_GITHUB_USERNAME: ${GREEN}$BK_GITHUB_USERNAME${NC}"
echo -e "BK_GITHUB_REPOSITORY: ${GREEN}$BK_GITHUB_REPOSITORY${NC}"
echo -e "BK_REPO_URL: ${GREEN}$BK_REPO_URL${NC}"
echo -e "BK_DIR: ${GREEN}$BK_DIR${NC}"
echo -e "BK_STREAM: ${GREEN}$BK_STREAM${NC}"
echo -e "BK_BRANCH: ${GREEN}$BK_BRANCH${NC}"
echo -e "BK_INITIALIZED: ${GREEN}$BK_INITIALIZED${NC}"
echo -e "config file: ${GREEN}$BK_DIR/vars.local.sh${NC}"
echo -e "PROJECT_ID: ${GREEN}$PROJECT_ID${NC}"
echo -e "PROJECT_NUMBER: ${GREEN}$PROJECT_NUMBER${NC}"
echo -e "REGION: ${GREEN}$REGION${NC}"
echo

echo -e "${CYAN}Info:${NC}"

if [ ! -d "${BK_DIR}/data" ]; then
    echo -e "data: ${RED}does not exist${NC}"
else
    echo -e "data: ${GREEN}exists${NC}"
    du -sh "${BK_DIR}/data"
fi

echo -e "git origin: ${GREEN}$(git -C "${BK_DIR}" config --get remote.origin.url 2>/dev/null)${NC}"